language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer update --prefer-source --no-interaction --no-progress

script:
  - phpunit
  - php coverage-checker.php clover.xml 75

after_success:
  - php vendor/bin/coveralls -v;