language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer update --prefer-source --no-interaction --no-progress

script:
  - mkdir -p build/logs
  - phpunit

after_script:
 - php vendor/bin/coveralls -v