language: php
php:
  - 7.0
  - 7.1

sudo: required

install:
  - composer update --prefer-source --no-interaction --no-progress

script:
  - phpunit
  - ./vendor/bin/phpmd src text cleancode, codesize, controversial, design, naming, unusedcode
